[opener]
Helix = [
  { run = "hx %s",block = true, desc = "Open"},
]

[open]
rules = [
  { mime = "text/*", use = "Helix" },
  { mime = "inode/x-empty", use = "Helix" },
  { url = "*.rmd", use = "Helix" },
  { url = "*.yml", use = "Helix" },
  { url = "*.yaml", use = "Helix" },
  { url = "*.conf", use = "Helix" },
  { url = "*.config", use = "Helix" },
  { url = "*.toml", use = "Helix" },
  { url = "*.nf", use = "Helix" },
  { mime = "video/*", use = "open" },
  { mime = "image/*", use = "open" },
  { mime = "application/pdf", use = "open" },
  # Catch-all rules should be LAST
  { url = "*", use = "open" },
]

[manager]
show_hidden = true

[plugin]
prepend_previewers = [
  { url = "*.rmd", run = "code" },
  { url = "*.conf", run = "code" },
]

[mgr]
show_hidden = true
